// Generated by gencpp from file rt_dynamixel_msgs/Error.msg
// DO NOT EDIT!


#ifndef RT_DYNAMIXEL_MSGS_MESSAGE_ERROR_H
#define RT_DYNAMIXEL_MSGS_MESSAGE_ERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt_dynamixel_msgs
{
template <class ContainerAllocator>
struct Error_
{
  typedef Error_<ContainerAllocator> Type;

  Error_()
    : error_code(0)
    , error_detail()  {
    }
  Error_(const ContainerAllocator& _alloc)
    : error_code(0)
    , error_detail(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_detail_type;
  _error_detail_type error_detail;



  enum {
    SER_INIT_FAILED = 1,
    OFFLINE_DETECT = 2,
  };


  typedef boost::shared_ptr< ::rt_dynamixel_msgs::Error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt_dynamixel_msgs::Error_<ContainerAllocator> const> ConstPtr;

}; // struct Error_

typedef ::rt_dynamixel_msgs::Error_<std::allocator<void> > Error;

typedef boost::shared_ptr< ::rt_dynamixel_msgs::Error > ErrorPtr;
typedef boost::shared_ptr< ::rt_dynamixel_msgs::Error const> ErrorConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt_dynamixel_msgs::Error_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rt_dynamixel_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rt_dynamixel_msgs': ['/home/rui/catkin_ws/src/rt_dynamixel_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt_dynamixel_msgs::Error_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_dynamixel_msgs::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_dynamixel_msgs::Error_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d97d350edf68e4d52368560032b073fd";
  }

  static const char* value(const ::rt_dynamixel_msgs::Error_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd97d350edf68e4d5ULL;
  static const uint64_t static_value2 = 0x2368560032b073fdULL;
};

template<class ContainerAllocator>
struct DataType< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt_dynamixel_msgs/Error";
  }

  static const char* value(const ::rt_dynamixel_msgs::Error_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 SER_INIT_FAILED=1\n\
int32 OFFLINE_DETECT=2\n\
\n\
int32 error_code\n\
string error_detail\n\
\n\
";
  }

  static const char* value(const ::rt_dynamixel_msgs::Error_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
      stream.next(m.error_detail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Error_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt_dynamixel_msgs::Error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt_dynamixel_msgs::Error_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "error_detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_detail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT_DYNAMIXEL_MSGS_MESSAGE_ERROR_H
