// Generated by gencpp from file rt_dynamixel_msgs/MotorSetting.msg
// DO NOT EDIT!


#ifndef RT_DYNAMIXEL_MSGS_MESSAGE_MOTORSETTING_H
#define RT_DYNAMIXEL_MSGS_MESSAGE_MOTORSETTING_H

#include <ros/service_traits.h>


#include <rt_dynamixel_msgs/MotorSettingRequest.h>
#include <rt_dynamixel_msgs/MotorSettingResponse.h>


namespace rt_dynamixel_msgs
{

struct MotorSetting
{

typedef MotorSettingRequest Request;
typedef MotorSettingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorSetting
} // namespace rt_dynamixel_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rt_dynamixel_msgs::MotorSetting > {
  static const char* value()
  {
    return "1c80fb3348bbb124fc72557f61e2f00b";
  }

  static const char* value(const ::rt_dynamixel_msgs::MotorSetting&) { return value(); }
};

template<>
struct DataType< ::rt_dynamixel_msgs::MotorSetting > {
  static const char* value()
  {
    return "rt_dynamixel_msgs/MotorSetting";
  }

  static const char* value(const ::rt_dynamixel_msgs::MotorSetting&) { return value(); }
};


// service_traits::MD5Sum< ::rt_dynamixel_msgs::MotorSettingRequest> should match 
// service_traits::MD5Sum< ::rt_dynamixel_msgs::MotorSetting > 
template<>
struct MD5Sum< ::rt_dynamixel_msgs::MotorSettingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rt_dynamixel_msgs::MotorSetting >::value();
  }
  static const char* value(const ::rt_dynamixel_msgs::MotorSettingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rt_dynamixel_msgs::MotorSettingRequest> should match 
// service_traits::DataType< ::rt_dynamixel_msgs::MotorSetting > 
template<>
struct DataType< ::rt_dynamixel_msgs::MotorSettingRequest>
{
  static const char* value()
  {
    return DataType< ::rt_dynamixel_msgs::MotorSetting >::value();
  }
  static const char* value(const ::rt_dynamixel_msgs::MotorSettingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rt_dynamixel_msgs::MotorSettingResponse> should match 
// service_traits::MD5Sum< ::rt_dynamixel_msgs::MotorSetting > 
template<>
struct MD5Sum< ::rt_dynamixel_msgs::MotorSettingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rt_dynamixel_msgs::MotorSetting >::value();
  }
  static const char* value(const ::rt_dynamixel_msgs::MotorSettingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rt_dynamixel_msgs::MotorSettingResponse> should match 
// service_traits::DataType< ::rt_dynamixel_msgs::MotorSetting > 
template<>
struct DataType< ::rt_dynamixel_msgs::MotorSettingResponse>
{
  static const char* value()
  {
    return DataType< ::rt_dynamixel_msgs::MotorSetting >::value();
  }
  static const char* value(const ::rt_dynamixel_msgs::MotorSettingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RT_DYNAMIXEL_MSGS_MESSAGE_MOTORSETTING_H
