(cl:in-package dyros_jet_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          WALK_MODE-VAL
          WALK_MODE
          COMPENSATOR_MODE-VAL
          COMPENSATOR_MODE
          IK_MODE-VAL
          IK_MODE
          HEEL_TOE-VAL
          HEEL_TOE
          FIRST_FOOT_STEP-VAL
          FIRST_FOOT_STEP
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          HEIGHT-VAL
          HEIGHT
          THETA-VAL
          THETA
          STEP_LENGTH_X-VAL
          STEP_LENGTH_X
          STEP_LENGTH_Y-VAL
          STEP_LENGTH_Y
          WALKING_PATTERN-VAL
          WALKING_PATTERN
))