; Auto-generated. Do not edit!


(cl:in-package dyros_jet_msgs-msg)


;//! \htmlinclude JointControlResult.msg.html

(cl:defclass <JointControlResult> (roslisp-msg-protocol:ros-message)
  ((is_reached
    :reader is_reached
    :initarg :is_reached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass JointControlResult (<JointControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dyros_jet_msgs-msg:<JointControlResult> is deprecated: use dyros_jet_msgs-msg:JointControlResult instead.")))

(cl:ensure-generic-function 'is_reached-val :lambda-list '(m))
(cl:defmethod is_reached-val ((m <JointControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dyros_jet_msgs-msg:is_reached-val is deprecated.  Use dyros_jet_msgs-msg:is_reached instead.")
  (is_reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointControlResult>) ostream)
  "Serializes a message object of type '<JointControlResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_reached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointControlResult>) istream)
  "Deserializes a message object of type '<JointControlResult>"
    (cl:setf (cl:slot-value msg 'is_reached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointControlResult>)))
  "Returns string type for a message object of type '<JointControlResult>"
  "dyros_jet_msgs/JointControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointControlResult)))
  "Returns string type for a message object of type 'JointControlResult"
  "dyros_jet_msgs/JointControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointControlResult>)))
  "Returns md5sum for a message object of type '<JointControlResult>"
  "92a498b18e821e639be1d4885d80f04c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointControlResult)))
  "Returns md5sum for a message object of type 'JointControlResult"
  "92a498b18e821e639be1d4885d80f04c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointControlResult>)))
  "Returns full string definition for message of type '<JointControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool is_reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointControlResult)))
  "Returns full string definition for message of type 'JointControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool is_reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointControlResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JointControlResult
    (cl:cons ':is_reached (is_reached msg))
))
