// Auto-generated. Do not edit!

// (in-package dyros_jet_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class JointControlResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.is_reached = null;
    }
    else {
      if (initObj.hasOwnProperty('is_reached')) {
        this.is_reached = initObj.is_reached
      }
      else {
        this.is_reached = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type JointControlResult
    // Serialize message field [is_reached]
    bufferOffset = _serializer.bool(obj.is_reached, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type JointControlResult
    let len;
    let data = new JointControlResult(null);
    // Deserialize message field [is_reached]
    data.is_reached = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dyros_jet_msgs/JointControlResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '92a498b18e821e639be1d4885d80f04c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    bool is_reached
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new JointControlResult(null);
    if (msg.is_reached !== undefined) {
      resolved.is_reached = msg.is_reached;
    }
    else {
      resolved.is_reached = false
    }

    return resolved;
    }
};

module.exports = JointControlResult;
