(cl:defpackage rt_dynamixel_msgs-srv
  (:use )
  (:export
   "MODESETTING"
   "<MODESETTING-REQUEST>"
   "MODESETTING-REQUEST"
   "<MODESETTING-RESPONSE>"
   "MODESETTING-RESPONSE"
   "MODESETTING (COPY)"
   "<MODESETTING (COPY)-REQUEST>"
   "MODESETTING (COPY)-REQUEST"
   "<MODESETTING (COPY)-RESPONSE>"
   "MODESETTING (COPY)-RESPONSE"
   "MOTORSETTING"
   "<MOTORSETTING-REQUEST>"
   "MOTORSETTING-REQUEST"
   "<MOTORSETTING-RESPONSE>"
   "MOTORSETTING-RESPONSE"
   "STATUS"
   "<STATUS-REQUEST>"
   "STATUS-REQUEST"
   "<STATUS-RESPONSE>"
   "STATUS-RESPONSE"
  ))

